### ISSUE TITLE
Environment & Boilerplate Set up

### ISSUE THREAD

**Issue by vlbee** [fac-13/stackMatch#10]
Set up Development Environment
- [x] Npm init, and install dev dependencies
- [x] set up linting
- [x] set up scripts - testing / coverage /  precommits / running/watching server 

Set up Boiler Plate
- [x] set up MVC file structure
- [x] set up Express Server - index.js / app.js
- [x] set up Model DB build and connection files - with testing db_build_test.js file
- [x] config.env file
- [x] set up testing and staging database on Heroku - create ```master``` and ```heroku-staging``` branch
- [x] set up travis CI - .yml file
- [ ] set up CSS/Sass preprocessor - issue #21

**Comment by LawEKS** [comment]
setting up SASS will be moved to later point in the sprint

**Comment by helenzhou6** [comment]
Closing since just #21 remaining
