### ISSUE TITLE
set up BEM and SASS compiler

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/stackMatch#21]
Related to user story #6
Ensure all team has the correct set up.

**Comment by LawEKS** [comment]
@jennah2121 wrote an amazing [guide](https://hackmd.io/nYbTUXuYSZOiTSoSHDp5BA?view) on using the [gulp](https://gulpjs.com) task runner.  
It has examples of using it with [Sass](https://sass-lang.com/) and [Browsersync](https://browsersync.io/).

These tools in combination will allow to automate the tasks of:
- compiling sass into css
- placing the file in the correct folder
- reloading the browser to reflect the changes made

**Comment by helenzhou6** [comment]
Great! Setting this up will close issue #10
