### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by tdoran** [fac-13/stackMatch#4]
Preliminary stack:
- Express, 
- OAuth (Passport)
- GraphQL API 
- GitHub
- PostgreSQL 
- Handlerbars
- BEM & SASS
- Tape
- Supertest

Let's investigate these stack options below too.
Add your research links in comments!

- [ ] Query builder for PostgreSQL
- [ ] Task runner - Gulp? Is this replaced by Webpack (module bundler)?
- [ ]  OAuth - (Passport)
- [ ] Github GraphQL
- [ ] Babel

**Comment by helenzhou6** [comment]
Closing this since tech stack has been decided (see README)
