### ISSUE TITLE
Error pages - 404 and 500

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/stackMatch#48]
Relate to user story #6
- [x] - 404 page
- [x] 500 page
- [x] `failureRedirect: '/'` - a page for unauthorised access

**Comment by helenzhou6** [comment]
- Includes adding `try` and `catch` where applicable
- In `index.js`, if there is an error should be handled appropriately (redirect to 500 error page?)

**Comment by vlbee** [comment]
I believe issue is just for adding error handling pages and middleware.  Ensuring all code is throwing errors correctly should not be part of this issue.
